site_name: COINS NES 2026.1
theme:
  name: material 

plugins:
  - search
  - awesome-pages
  - minify
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

nav:
  - Início: index.md
